version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  target-branch: master
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  target-branch: "4.0"
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  target-branch: "3.1"
  ignore:
  - dependency-name: jakarta.enterprise:jakarta.enterprise.cdi-api
    versions:
    - ">= 3.a, < 4"
  - dependency-name: jakarta.inject:jakarta.inject-api
    versions:
    - ">= 2.a, < 3"
  - dependency-name: jakarta.persistence:jakarta.persistence-api
    versions:
    - ">= 3.a, < 4"
